/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventschedulerclient;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author anshal
 */
public class eventsPanel extends javax.swing.JFrame {

    /**
     * Creates new form eventsPanel
     */
    int venueId;
    DataInputStream dis;
    
    DataOutputStream dos;
    DefaultListModel eN=new DefaultListModel();
    DefaultListModel sT=new DefaultListModel();
    DefaultListModel eT=new DefaultListModel();
    DefaultListModel hN=new DefaultListModel();
    DefaultListModel dL=new DefaultListModel();
    public eventsPanel(DataInputStream dis,DataOutputStream dos,int venueId) {
        initComponents();
        this.dis=dis;
        this.dos=dos;
        eventName.setModel(eN);
        startingAt.setModel(sT);
        endingAt.setModel(eT);
        dateList.setModel(dL);
        hostedBy.setModel(hN);
        this.venueId=venueId;
        decorate();
    }
    public void decorate(){
        try {
            dos.writeInt(venueId);
            while(true){
                String eName=dis.readUTF();
                if(eName.equals("-1"))
                    break;
                String start=dis.readUTF();
                String end=dis.readUTF();
                String hostName=dis.readUTF();
                String date=dis.readUTF();
                eN.addElement(eName);
                sT.addElement(start.substring(0,2)+":"+start.substring(2));
                eT.addElement(end.substring(0,2)+":"+end.substring(2));
                hN.addElement(hostName);
                dL.addElement(date);
            }
        } catch (IOException ex) {
            Logger.getLogger(eventsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        endingAt = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        eventName = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        startingAt = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        dateList = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        hostedBy = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Event Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, 106, -1));

        jLabel2.setText("Starting At");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 31, -1, -1));

        jLabel3.setText("Ending At");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 31, -1, -1));

        jLabel4.setText("hosted By");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 31, -1, -1));

        endingAt.setBackground(new java.awt.Color(152, 251, 152));
        endingAt.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        endingAt.setForeground(new java.awt.Color(0, 128, 0));
        jScrollPane2.setViewportView(endingAt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 54, 137, 410));

        eventName.setBackground(new java.awt.Color(152, 251, 152));
        eventName.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        eventName.setForeground(new java.awt.Color(0, 128, 0));
        jScrollPane3.setViewportView(eventName);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 134, 410));

        startingAt.setBackground(new java.awt.Color(152, 251, 152));
        startingAt.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        startingAt.setForeground(new java.awt.Color(0, 128, 0));
        jScrollPane4.setViewportView(startingAt);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 54, 138, 410));

        dateList.setBackground(new java.awt.Color(152, 251, 152));
        dateList.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        dateList.setForeground(new java.awt.Color(0, 128, 0));
        jScrollPane5.setViewportView(dateList);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 54, 144, 410));

        hostedBy.setBackground(new java.awt.Color(152, 251, 152));
        hostedBy.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        hostedBy.setForeground(new java.awt.Color(0, 128, 0));
        jScrollPane6.setViewportView(hostedBy);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 54, 144, 410));

        jLabel5.setText("date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 31, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList dateList;
    private javax.swing.JList endingAt;
    private javax.swing.JList eventName;
    private javax.swing.JList hostedBy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList startingAt;
    // End of variables declaration//GEN-END:variables
}
