/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventschedulerclient;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author anshal
 */
public class eventDetails extends javax.swing.JFrame {

    /**
     * Creates new form eventDetails
     */
    int eventId;
    DataInputStream dis;
    DataOutputStream dos;
    DefaultListModel pending=new DefaultListModel();
    DefaultListModel accepted=new DefaultListModel();
    DefaultListModel rejected=new DefaultListModel();
    
    public final int REQUEST_STATUS=12;
    public eventDetails(int eventId,DataInputStream dis,DataOutputStream dos) {
        
        initComponents();
        this.eventId=eventId;
        pendingList.setModel(pending);
        acceptedList.setModel(accepted);
        rejectedList.setModel(rejected);
        this.dis=dis;
        this.dos=dos;
        requestStats();
    }
    public void requestStats(){
        try {
            System.out.println("here eventId is"+eventId);
            dos.writeInt(REQUEST_STATUS);
            dos.writeInt(eventId);
            int sz=dis.readInt();
            System.out.println(sz);
            for(int i=0;i<sz;i++){
                String tmp=dis.readUTF();
                pending.addElement(tmp);
            }
            sz=dis.readInt();
             System.out.println(sz);
            for(int i=0;i<sz;i++){
                String tmp=dis.readUTF();
                accepted.addElement(tmp);
            }
           
            sz=dis.readInt();
             System.out.println("fansha hun :(");
             System.out.println(sz);
            for(int i=0;i<sz;i++){
                String tmp=dis.readUTF();
                rejected.addElement(tmp);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(eventDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rejectedList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        acceptedList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendingList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rejectedList.setBackground(new java.awt.Color(255, 160, 122));
        rejectedList.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        rejectedList.setForeground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(rejectedList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 41, 111, 444));

        acceptedList.setBackground(new java.awt.Color(152, 251, 152));
        acceptedList.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        acceptedList.setForeground(new java.awt.Color(0, 128, 0));
        jScrollPane2.setViewportView(acceptedList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 41, 111, 444));

        pendingList.setBackground(new java.awt.Color(175, 238, 238));
        pendingList.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        pendingList.setForeground(new java.awt.Color(70, 130, 180));
        jScrollPane3.setViewportView(pendingList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 41, 111, 444));

        jLabel1.setText("     Accepted");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 12, 111, -1));

        jLabel2.setText("Rejected");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 12, -1, -1));

        jLabel3.setText("pending");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 12, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList acceptedList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList pendingList;
    private javax.swing.JList rejectedList;
    // End of variables declaration//GEN-END:variables
}
