/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventschedulerclient;

import java.io.DataInputStream;
import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anshal
 */
public class Login_Reg_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Login_Reg_Panel
     */
    Socket sock;
    DataInputStream ldis;
    DataOutputStream ldos;
    
    public Login_Reg_Panel() {
       
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_uname = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        R_pass = new javax.swing.JTextField();
        R_uname = new javax.swing.JTextField();
        R_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        L_pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(638, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_uname.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        getContentPane().add(L_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 30));

        Login.setBackground(new java.awt.Color(152, 251, 152));
        Login.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        Login.setForeground(new java.awt.Color(0, 128, 0));
        Login.setText(" LogIn");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 90, 30));

        R_pass.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        getContentPane().add(R_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 300, 30));

        R_uname.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        getContentPane().add(R_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 300, 30));

        R_name.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        getContentPane().add(R_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 300, 30));

        jLabel1.setText("Password:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 130, 20));

        jLabel2.setText("UserName:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 130, 20));

        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, 20));

        Register.setBackground(new java.awt.Color(100, 149, 237));
        Register.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        Register.setForeground(new java.awt.Color(0, 0, 205));
        Register.setText("Register Yourself !");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 300, 30));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 540, 170));

        L_pass.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        getContentPane().add(L_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 160, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 790, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        try {                                      
            // TODO add your handling code here:
            sock=new Socket("localhost",14531);
            ldis=new DataInputStream(sock.getInputStream());
            ldos=new DataOutputStream(sock.getOutputStream());
            String Uname,Pass;
            Uname=L_uname.getText();
            int clientId,alloted_port;
            Pass=new String(L_pass.getPassword());
            System.out.println(Pass);
            try {
                ldos.writeInt(1);
                ldos.writeUTF(Uname);
                ldos.writeUTF(Pass);
                int server_response=ldis.readInt();
                if(server_response==1){
                    System.out.println("Wrong Username");
                }
                else if(server_response==2){
                    System.out.println("Password didn't Match");
                }
                else{
                    clientId=ldis.readInt();
                    alloted_port=ldis.readInt();
                    System.out.println("logged In :)");
                    System.out.println("ClientId - "+clientId+"\n"+"alloted_port - "+alloted_port);
                    UserHome uhome=new UserHome(clientId, Uname, Uname,alloted_port);
                    uhome.setVisible(true);
                    uhome.setLocationRelativeTo(null);
                    ldis.close();
                    ldos.close();
                    sock.close();
                    this.dispose();
                }
            } catch (IOException ex) {
                Logger.getLogger(Login_Reg_Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(Login_Reg_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_LoginActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        try {
            // TODO add your handling code here:
            sock=new Socket("localhost",14531);
            ldis=new DataInputStream(sock.getInputStream());
                ldos=new DataOutputStream(sock.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(Login_Reg_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        String Uname,Pass,Name;
        Name=R_name.getText();
        Uname=R_uname.getText();
        Pass=R_pass.getText();
        try {
            ldos.writeInt(2);
            ldos.writeUTF(Name);
            ldos.writeUTF(Uname);
            ldos.writeUTF(Pass);
            int response_code=ldis.readInt();
            if(response_code==0){
                System.out.println("Success");
            }
            else{
                System.out.println("Wrong username");
            }
        } catch (IOException ex) {
            Logger.getLogger(Login_Reg_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Reg_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Reg_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Reg_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Reg_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Reg_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField L_pass;
    private javax.swing.JTextField L_uname;
    private javax.swing.JButton Login;
    private javax.swing.JTextField R_name;
    private javax.swing.JTextField R_pass;
    private javax.swing.JTextField R_uname;
    private javax.swing.JButton Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
