/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventschedulerclient;

import java.io.DataOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anshal
 */
public class newEvent extends javax.swing.JFrame {

    /**
     * Creates new form newEvent
     */
    public final int NEW_EVENT=4;
    public int clientId;
    public int slotId;
    public int venueId;
    int bookingId;
    public String date;
    DataOutputStream dos;
    UserHome uh;
    public newEvent(int clientId,int slotId,int venueId,String date,DataOutputStream dos,int bookingId,UserHome uh) {
        initComponents();
        this.clientId=clientId;
        this.slotId=slotId;
        this.bookingId=bookingId;
        this.venueId=venueId;
        this.date=date;
        this.dos=dos;
        this.uh=uh;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        eventTitle = new javax.swing.JTextField();
        createEvent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        privacy = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 128, 0));
        jLabel1.setText("Event Title: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 44, -1, -1));
        getContentPane().add(eventTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 39, 240, -1));

        createEvent.setBackground(new java.awt.Color(152, 251, 152));
        createEvent.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        createEvent.setForeground(new java.awt.Color(0, 128, 0));
        createEvent.setText("Create Event");
        createEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventActionPerformed(evt);
            }
        });
        getContentPane().add(createEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 240, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 128, 0));
        jLabel3.setText("Event Title: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 44, -1, -1));

        privacy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Public", "Private" }));
        getContentPane().add(privacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 101, 30));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 128, 0));
        jLabel4.setText("Privacy");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -3, 440, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventActionPerformed
        try {
            // TODO add your handling code here:
            dos.writeInt(NEW_EVENT);
            dos.writeInt(clientId);
            dos.writeInt(venueId);
            dos.writeInt(slotId);
            int pri=privacy.getSelectedIndex();
            String s=pri+eventTitle.getText();
            dos.writeUTF(s);
            dos.writeInt(bookingId);
            System.out.println("I am done :)");
            uh.updateBookedSlots();
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(newEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_createEventActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEvent;
    private javax.swing.JTextField eventTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox privacy;
    // End of variables declaration//GEN-END:variables
}
